# Generated by Django 3.0.8 on 2020-08-16 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_myuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='display_pic',
            field=models.ImageField(default='python.jpg', upload_to=''),
        ),
    ]
