# Generated by Django 3.0.8 on 2020-08-17 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_myuser_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'Apssdc User', 'verbose_name_plural': 'Apssdc Users'},
        ),
    ]
