# Generated by Django 3.0.8 on 2020-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_auto_20200730_0623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='offer_price',
        ),
        migrations.AddField(
            model_name='course',
            name='original_price',
            field=models.FloatField(default=0.0),
        ),
    ]
