# Generated by Django 3.0.8 on 2020-07-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_auto_20200730_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='original_price',
            field=models.FloatField(),
        ),
    ]
