# Generated by Django 3.0.8 on 2020-08-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_auto_20200730_0639'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(default='', max_length=11),
        ),
    ]
