# Generated by Django 3.0.8 on 2020-08-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_lesson_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='viewed',
            field=models.TextField(default=[]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_id',
            field=models.CharField(max_length=11),
        ),
    ]
