# Generated by Django 3.0.8 on 2020-08-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_auto_20200807_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='viewed',
            field=models.BooleanField(),
        ),
    ]
