# Generated by Django 3.0.8 on 2020-08-07 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lms', '0008_auto_20200807_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='viewed',
        ),
        migrations.CreateModel(
            name='CourseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_lessons', models.ManyToManyField(related_name='completed_lessons', to='lms.Lesson')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lms.Course')),
                ('current_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_lesson', to='lms.Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
