# Generated by Django 3.0.8 on 2020-08-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0010_auto_20200807_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestatus',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='completed_lessons', to='lms.Lesson'),
        ),
    ]
