# Generated by Django 3.0.8 on 2020-08-07 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_auto_20200807_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.TextField(default=''),
        ),
    ]
