# Generated by Django 3.0.8 on 2020-08-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0013_auto_20200807_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='coursestatus',
            options={'verbose_name_plural': 'Course Status'},
        ),
    ]
