# Generated by Django 3.0.8 on 2020-08-10 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0014_auto_20200810_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lms.Category'),
            preserve_default=False,
        ),
    ]
