# Generated by Django 3.0.8 on 2020-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0015_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img380x256',
            field=models.ImageField(default='market.jpg', upload_to=''),
        ),
    ]
