# Generated by Django 3.0.8 on 2020-08-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0016_category_img380x256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='pdf',
            field=models.FileField(default='mozilla.pdf', upload_to=''),
        ),
    ]
