# Generated by Django 3.0.8 on 2020-08-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0017_auto_20200814_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='img293x274',
            field=models.ImageField(upload_to='', verbose_name='img380x256'),
        ),
    ]
