# Generated by Django 3.0.8 on 2020-08-20 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0018_auto_20200817_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='market.jpg', upload_to='')),
                ('about', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('linkedin', models.URLField()),
                ('quora', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(blank=True, null=True, to='lms.FAQ'),
        ),
        migrations.AddField(
            model_name='course',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='lms.Project'),
        ),
        migrations.AddField(
            model_name='course',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lms.Trainer'),
        ),
    ]
