# Generated by Django 3.0.8 on 2020-08-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0019_auto_20200820_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='faq',
            field=models.ManyToManyField(blank=True, to='lms.FAQ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='project',
            field=models.ManyToManyField(blank=True, to='lms.Project'),
        ),
    ]
