# Generated by Django 3.0.8 on 2020-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0025_auto_20200823_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.TextField(verbose_name='Key Skills'),
        ),
    ]
